language: groovy
jdk:
    - oraclejdk8
addons:
    ssh_known_hosts: serebryanskiy.site
before_install:
    - openssl aes-256-cbc -K $encrypted_0e03e4d6fca5_key -iv $encrypted_0e03e4d6fca5_iv -in deploy_rsa.enc -out deploy_rsa -d
    - ls $TRAVIS_BUILD_DIR
before_deploy:
    - eval "$(ssh-agent -s)"
    - chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
    - ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
deploy:
    provider: script
    skip_cleanup: true
    script: scp build/libs/finance-template.war deployer@serebryanskiy.site:~/tomcat8/finance-template.war
    on:
        branch: template